format long
sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^...
    (sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^...
    (sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^...
    (sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^...
    (sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^(sqrt(2)^...
    (sqrt(2)^(sqrt(2))))))))))))))))))))))))))))))))